### ISSUE TITLE
[FEATURE] Add Pagination to Job Listings

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/JobzQuest#1]
### Description

As JobzQuest continues to grow, it's important to provide users with an efficient way to navigate through job listings. This issue involves adding pagination functionality to the job listings page, allowing users to view a limited number of jobs per page and easily navigate to the next or previous pages. By implementing pagination, you can improve the performance and usability of the JobzQuest platform.

Skills - HTML, CSS, JavaScript

To get started on this issue, you can follow these steps:

- Identify the HTML structure and CSS classes associated with the job listings section.
- Implement a JavaScript function that handles the logic for pagination, including calculating the number of pages and which job listings to display on each page.
- Update the HTML markup and CSS styles to accommodate the pagination feature, including the addition of page navigation buttons or links.
- Test the pagination functionality by verifying that the correct number of job listings are displayed per page and that the navigation buttons work as intended.
- Consider any additional features such as showing the total number of job listings or providing options to customize the number of listings per page.
- Submit a pull request with the updated code and request feedback from the project maintainers.

**Comment by priya1011** [comment]
@theritikchoure I would like to take on this issue and implement the pagination functionality for the job listings page.
I will create a pull request with the changes once I have completed the implementation. Looking forward to contributing to the project!

**Comment by theritikchoure** [comment]
Ok @priya1011 I am assigning
